server:
  port: 8082
spring:
  application:
    name: contract-check-service
  cloud:
    stream:
      binder:
        brokers: "http://localhost:9092"
        autoCreateTopics: true
        autoAddPartitions: true
      bindings:
        contractCheckProcess-in-0.destination: checking-contract
        contractCheckProcess-out-0.destination: processing-contract
      kafka:
        binder:
          enableObservation: true

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    root: INFO
    org.apache.kafka: OFF

