server:
  port: 8083
spring:
  application:
    name: contract-executing-service
  cloud:
    stream:
      binder:
        brokers: "http://localhost:9092"
        autoCreateTopics: true
        autoAddPartitions: true
      bindings:
        contractExecutingProcess-in-0.destination: executing-contract
        contractExecutingProcess-out-0.destination: processing-contract
      kafka:
        binder:
          enableObservation: true

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    root: INFO
    org.apache.kafka: OFF

